#theme: jekyll-theme-slate
#theme: jekyll-theme-architect
remote_theme: daattali/beautiful-jekyll
#base_url: michelif/ETH-Students-instuctions

title: 'Instructions for ETH students'
header_pages:
- index.md
